Task 1:  Setting up the environment
bozhnyukAlex/formal-lang-course pull request #1
Opened 2021-09-04 21:46 UTC by bozhnyukAlex

- Graph utilitites implemented
- Unit tests provided
- Console application abilities implemented

2021-09-06 13:10 UTC, vdshk requested changes
Также есть пара глобальных замечаний.

* Запускаться `REPL` должен через `python -m project`. Сейчас так не работает.

* >   - [ ] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах.

    Именно **по имени**. В наборе данных у графов есть имена. Такие как `geospecies`, `pizza`, `enzyme`. См. [Get a real graph](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#get-a-real-graph)
    
* Копируйте из `tasks` полностью описание задачи в комментарий вашего PR и проставляйте чекбоксики, пожалуйста. Так будет и вам и мне проще видеть, что требовалось сделать и что уже сделано.

* Не забудьте написать в `project/README.md` как запускать ваше **консольное приложение**.

* Убедитесь, что ваши тесты покрывают все возможные крайние случаи.
    
> Мой комментарий на русском языке, так как курс читается на русском языке.
Если вы согласны перейти на английский, напишите мне об этом, пожалуйста, в комментариях.

2021-09-06 13:10 UTC, vivalerievich commented on .github/workflows/test_running.yml
> +name: Check code style
У Вас имена action'ов одинаковые. Это вызывает неоднозначность.

2021-09-06 13:10 UTC, vivalerievich commented on .github/workflows/test_running.yml
> +        python-version: [ 3.8 ]
Добавьте в матрицу `ubuntu-latest`, `macos-latest`, `windows-latest`, чтобы тестировать ваше решение на всех платформах. Мы в задачах будем использовать только кросс-платформенные библиотеки, поэтому проблем не будет.

2021-09-06 13:10 UTC, vivalerievich commented on project/__init__.py
> -print("import sources directory")
Здесь должны быть импорты основных функций пакета.
Что-то вроде
```python
import project.commands
from project.commands import *

import project.console
from project.console import *
```
Заодно пропишите в подмодулях `__all__`

2021-09-06 13:10 UTC, vivalerievich commented on project/commands.py
> +    """
Используйте [`NumPy docstrings`](https://numpydoc.readthedocs.io/en/latest/format.html).
Минимально требуется: `1. Short summary`, `4. Parameters`, `5. Returns` или `6. Yields`

2021-09-06 13:10 UTC, vivalerievich commented on project/commands.py
> +    """
И так для всех функций и классов.

2021-09-06 13:10 UTC, vivalerievich commented on project/commands.py
> +    filename, nodes_first_num, nodes_second_num, label_first, label_second
Прописывайте, пожалуйста, для параметров `type hints`

2021-09-06 13:10 UTC, vivalerievich commented on project/__main__.py
> +    run()
Документации не хватает

2021-09-06 13:10 UTC, vivalerievich commented on project/commands.py
> +    print(info)
Старайтесь разделять пыстуми строками осмысленные блоки текста, а не слепливать всё в одно полотно.
```suggestion
    file = Path(graph_filename)
    _, extension = os.path.splitext(graph_filename)
    
    if not file.is_file():
        raise ExecutionException("No such file exists!")
        
    if extension != ".dot":
        raise ExecutionException("Wrong extension of file!")
        
    pydot_graph = pydot.graph_from_dot_file(graph_filename)[0]
    
    graph = networkx.drawing.nx_pydot.from_pydot(pydot_graph)
    
    info = get_graph_info(graph)
    
    print("Information about graph")
    print(info)
```

2021-09-06 13:10 UTC, vivalerievich commented on project/commands.py
> +    filename, nodes_first_num, nodes_second_num, label_first, label_second
Почему `filename` первым параметром?

2021-09-06 13:10 UTC, vivalerievich commented on project/commands.py
> +    print("Graph has been created and saved.")
См. замечание выше.
```suggestion
    file = Path(filename)
    
    if not file.is_file():
        open(filename, "w")
        
    generate_and_save_two_cycles(
        int(nodes_first_num),
        int(nodes_second_num),
        (label_first, label_second),
        filename,
    )
    
    print("Graph has been created and saved.")
```

2021-09-06 13:10 UTC, vivalerievich commented on project/console.py
> +command_names = ["graph_info", "create_and_save", "quit"]
По заданию у вас должны быть следующие команды. (названия примерные)
```suggestion
command_names = ["get_graph_info", "create_two_cycles_graph", "save_to_dot", "quit"]
```

2021-09-06 13:10 UTC, vivalerievich commented on project/console.py
> +            raise InputException("Error in argument's number!")
См. замечание выше.
```suggestion
    current_command_name = input_split[0]
    
    if current_command_name not in command_names:
        raise InputException("Command not found!")
        
    if current_command_name == command_names[0]:
        if len(input_split) != 2:
            raise InputException("Error in argument's number!")
    elif current_command_name == command_names[1]:
        if len(input_split) != 6:
            raise InputException("Error in argument's number!")
            
        if not input_split[2].isnumeric() or not input_split[3].isnumeric():
            raise InputException("Wrong types of arguments!")
    elif current_command_name == command_names[2]:
        if len(input_split) != 1:
            raise InputException("Error in argument's number!")
```

2021-09-06 13:10 UTC, vivalerievich commented on project/graphs.py
> +    graph.write_raw(filename)
> - [ ] По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).

На самом деле здесь две задачи:
1. По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph)
2. Cохранять граф в указанный файл в формате DOT (использовать pydot).

Соответственно должно быть две функции, а не одна. Не забудьте, что эти для этих функций тоже нужны тесты.

2021-09-06 13:10 UTC, vivalerievich commented on project/graphs.py
> +    graph.write_raw(filename)
Также стоит возвращать из функции полный путь до файла.

2021-09-06 13:10 UTC, vivalerievich commented on requirements.txt
> +networkx
`networkx` уже есть в зависимостях у `cfpq_data`. Почему вы его добавили?
```suggestion
```

2021-09-06 13:10 UTC, vivalerievich commented on resources/example_saving.dot
> + digraph  {
Непонятно для чего используется этот файл. Да и папка `resources` в целом.
Если вы хотите написать тест, проверяющий, что вы правильно сохраняете файл в формате DOT, тот этот файл должен быть в папке `tests`. Желательно в `tests/data`.

2021-09-06 13:10 UTC, vivalerievich commented on tasks/task1.md
`tasks` трогать не стоит

2021-09-06 13:10 UTC, vivalerievich commented on tests/test_basic.py
> -import pytest
Файл `test_basic` был в качестве наглядного примера. Далее его стоит удалить

2021-09-06 13:10 UTC, vivalerievich commented on project/graphs.py
> +class GraphInfo:
Нехватает документации к классу

2021-09-06 13:10 UTC, vivalerievich commented on tests/test_basic.py
> +    assert g_info.labels == {"one", "two", "three"}
В unit тестах лучше придерживаться правила один assert на тест.

2021-09-06 13:10 UTC, vivalerievich commented on tests/test_basic.py
> +    generate_and_save_two_cycles(10, 15, ("a", "b"), "resources/example_saving.dot")
Что этот тест проверяет?
Как минимум стоит проверять то, что тот граф, который вы сохраняете, совпадает с тем, что вы ожидаете увидеть как он сохранится. По сути должен быть `graph_expected.dot` в `tests/data`.

2021-09-06 13:20 UTC, bozhnyukAlex commented
Согласен перейти на английский

2021-09-06 15:07 UTC, bozhnyukAlex commented on project/commands.py
> +    filename, nodes_first_num, nodes_second_num, label_first, label_second
Я могу его сделать последним, но почему нельзя первым? Так не принято?

2021-09-06 15:37 UTC, bozhnyukAlex commented on .github/workflows/test_running.yml
> +name: Check code style
Done

2021-09-06 15:37 UTC, bozhnyukAlex commented on .github/workflows/test_running.yml
> +        python-version: [ 3.8 ]
Done

2021-09-06 15:37 UTC, bozhnyukAlex commented on project/__init__.py
> -print("import sources directory")
Done

2021-09-06 16:08 UTC, bozhnyukAlex commented on project/graphs.py
> +class GraphInfo:
Done

2021-09-06 16:08 UTC, bozhnyukAlex commented on tasks/task1.md
Done

2021-09-06 16:10 UTC, bozhnyukAlex commented on requirements.txt
> +networkx
Done

2021-09-06 16:11 UTC, bozhnyukAlex commented on project/__main__.py
> +    run()
Done

2021-09-06 16:11 UTC, bozhnyukAlex commented on project/commands.py
> +    """
Done

2021-09-06 17:12 UTC, bozhnyukAlex commented on project/graphs.py
> +    graph.write_raw(filename)
Тогда тут вопрос по формулировке: как мы должны поступать после построения? Должны ли мы иметь возможность смотреть информацию не только о графах из датасетов, но и созданных через консоль? Если да, выходит в функцию генерации надо передавать еще и имя графа?

2021-09-06 17:16 UTC, bozhnyukAlex commented on project/graphs.py
> +    graph.write_raw(filename)
И еще: имена графов из датасетов только [тут](https://jetbrains-research.github.io/CFPQ_Data/dataset/RDF.html) перечислены? То есть, те графы, что можно получить через `cfpq_data.graph_from_dataset`?

2021-09-07 07:09 UTC, bozhnyukAlex commented on tests/test_basic.py
> +    assert g_info.labels == {"one", "two", "three"}
Done

2021-09-07 07:10 UTC, bozhnyukAlex commented on tests/test_basic.py
> -import pytest
Done

2021-09-07 07:10 UTC, bozhnyukAlex commented on project/commands.py
> +    filename, nodes_first_num, nodes_second_num, label_first, label_second
Done

2021-09-07 07:10 UTC, bozhnyukAlex commented on project/commands.py
> +    print(info)
Done

2021-09-07 07:10 UTC, bozhnyukAlex commented on project/commands.py
> +    print("Graph has been created and saved.")
Done

2021-09-07 07:10 UTC, bozhnyukAlex commented on project/console.py
> +command_names = ["graph_info", "create_and_save", "quit"]
Done

2021-09-07 07:10 UTC, bozhnyukAlex commented on project/console.py
> +            raise InputException("Error in argument's number!")
Done

2021-09-07 07:10 UTC, bozhnyukAlex commented on project/graphs.py
> +    graph.write_raw(filename)
Done

2021-09-07 07:11 UTC, bozhnyukAlex commented on resources/example_saving.dot
> + digraph  {
Done

2021-09-07 10:40 UTC, bozhnyukAlex commented on tests/test_basic.py
> +    generate_and_save_two_cycles(10, 15, ("a", "b"), "resources/example_saving.dot")
Done

2021-09-07 17:47 UTC, vdshk requested changes
В целом всё супер. Исправьте четыре мелких замечания и можно будет засчитывать.

2021-09-07 17:47 UTC, vdshk commented on project/__main__.py
> +    Main function, when we run console application
```suggestion
    Main function, where we run console application
```

2021-09-07 17:47 UTC, vdshk commented on project/commands.py
> +            Explanation of the error
```suggestion
    message: str
        Explanation of the error
```

2021-09-07 17:47 UTC, vdshk commented on project/commands.py
> +__all__ = ["ExecutionException"]
Думаю здесь не только `ExecutionException` должен быть

2021-09-07 17:47 UTC, vdshk commented on project/console.py
> +from project.commands import ExecutionException
Лучше сделать либо

```python
import project as p
```

либо

```python
from project.commands import <всё, что нужно>
```

2021-09-07 19:35 UTC, bozhnyukAlex commented on project/__main__.py
> +    Main function, when we run console application
Done

2021-09-07 19:35 UTC, bozhnyukAlex commented on project/commands.py
> +            Explanation of the error
Done

2021-09-07 19:35 UTC, bozhnyukAlex commented on project/commands.py
> +__all__ = ["ExecutionException"]
Done

2021-09-07 19:35 UTC, bozhnyukAlex commented on project/console.py
> +from project.commands import ExecutionException
Done

2021-09-07 20:00 UTC, vdshk requested changes
Все отлично. Осталось замечание про импорты с прошлого раза, видимо вы меня неправильно поняли (см. [PEP8](https://www.python.org/dev/peps/pep-0008/#imports)). Как исправите это, - будет зачтено.

2021-09-07 20:00 UTC, vivalerievich commented on project/commands.py
> +from project.graphs import *
Еще раз. Вы меня наверное неправильно поняли. Так делать не стоит (см. [PEP8](https://www.python.org/dev/peps/pep-0008/#imports)).

Вы можете сделать либо (что проще)

```python
import project as p
```

либо

```python
from project.graphs import GraphInfo, graph_info, generate_two_cycles_graph
```

2021-09-07 20:00 UTC, vivalerievich commented on project/console.py
> +from project.commands import *
Так делать не стоит (см. [PEP8](https://www.python.org/dev/peps/pep-0008/#imports)).

Проще оставить 

```python
import project as p
```

2021-09-07 20:31 UTC, bozhnyukAlex commented on project/console.py
> +from project.commands import *
Если сделать точно так, то появляются ошибки при импорте модулей. Я попробовал слегка по другому сделать в коммите.

2021-09-08 04:29 UTC, vdshk approved these changes
Молодец :+1:

> Советую, чтобы не сохранять все исправления в истории, сделать `Squash and merge`

2021-09-08 06:33 UTC, merged