[Task 2] Построение детерминированного конечного автомата по регулярному выражению
bozhnyukAlex/formal-lang-course pull request #2
Opened 2021-09-09 17:05 UTC by bozhnyukAlex

## Задача

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
- [x] Добавить необходимые тесты.

2021-09-13 08:31 UTC, vdshk requested changes
Глобально всё хорошо :+1:
Но есть пара небольших замечаний, которые стоит поправить ;)

2021-09-13 08:31 UTC, vivalerievich commented on project/regex.py
> +    return dfa
> - [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
  
  Именно **минимального**. Тут вы не минимальный получаете.

2021-09-13 08:31 UTC, vdshk commented on tests/test_regex.py
> +    ]
Посмотрите, пожалуйста, на [`@pytest.mark.parametrize`](https://docs.pytest.org/en/6.2.x/parametrize.html) и добавьте больше регулярных выражений (с крайними случаями, например `regex = ""`)

2021-09-13 08:31 UTC, vdshk commented on tests/test_regex.py
> +    assert all(dfa.accepts(word) for word in test_words)
Также стоит добавить тесты на минимальность построенного ДКА. А также тесты на проверку того, что тот ДКА, который вы получаете из функции совпадает с ДКА, который вы ожидаете получить.

2021-09-14 07:00 UTC, vdshk requested changes
Всё отлично :+1:
Как исправите одно мелкое замечание, -- будет зачтено :)

- [x] Еще было бы здорово добавить `pyformlang` в `requirements.txt`

2021-09-14 07:00 UTC, vdshk commented on project/regex.py
> +    """
Нехватает `Raises` секции

2021-09-14 08:57 UTC, vdshk approved these changes
Зачтено :+1:

2021-09-14 09:13 UTC, merged