[Task 4] RPQ
bozhnyukAlex/formal-lang-course pull request #4
Opened 2021-09-28 18:02 UTC by bozhnyukAlex

## Задача

- [ ] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать алгоритм пересечения двух конечных автоматов через тензорное произведение.
- [ ] На основе реализованного алгоритма реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе.
  - Для конструирования регулярного запроса использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
  - Для преобразования графа использовать результаты [Задачи 3](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task3.md).
- [ ] Добавить необходимые тесты.

2021-10-04 11:39 UTC, vdshk requested changes
Непонятно почему вы в `test_query` используете всего 1 граф. Это не очень хорошо. И довольно важно проверять различные сценарии запроса `rpq`. Как например `rpq` с пустым графом и другие крайние случаи.

И `docstrings` у вас местами почему-то пропали.

Поскольку есть существенные замечания и `review` запрошено после мягкого дедлайна, то максимум будет `1/2` баллов за задачу :disappointed:

2021-10-04 11:39 UTC, vdshk commented on project/boolean_matrices.py
> +        automaton = NondeterministicFiniteAutomaton()
`docstring`?

2021-10-04 11:39 UTC, vdshk commented on project/boolean_matrices.py
> +        automaton = NondeterministicFiniteAutomaton()
И в остальных функциях\методах

2021-10-04 11:39 UTC, vdshk commented on tests/test_rpg.py
> +    actual_rpq = rpq(default_graph, regex, start_nodes, final_nodes)
А почему вы всего один граф в тесте используете? Попробуйте подумать о разных крайних случаях

2021-10-06 15:00 UTC, vadyushkins approved these changes
Зачтено

2021-10-06 15:02 UTC, merged