Task 5: RPQ experiments
bozhnyukAlex/formal-lang-course pull request #5
Opened 2021-10-08 15:35 UTC by bozhnyukAlex

## Задача

Задача посвящена анализу производительности различных реализаций алгоритма решения задачи достижимости между всеми парами вершин с регулярными ограничениями через тензорное произведение.

Решение данной задачи оформляется как Python notebook на [Google colab](https://colab.research.google.com/). Для того, чтобы обеспечить возможность проверки, решение делается доступным по ссылке, ссылка добавляется в readme репозитория, в котором выполняются остальные задачи, делается реквест с этим изменением.

Решением является не просто код, но отчёт об экспериментальном исследовании, который должен являться связанным текстом и содержать (как минимум) следующие разделы:
- Постановка задачи
- Выбор и описание исследуемых решений
- Описание набора данных для экспериментов
  - Графы
  - Запросы
- Описание эксперимента
  - Оборудование
  - Что и как замерялось
- Результаты экспериментов
  - Графики, таблицы
- Анализ результатов экспериментов
  - Какой алгоритм и в каких случаях лучше? Почему?

- [ ] Используя [pyCuBool](https://pypi.org/project/pycubool/) реализовать алгоритм пересечения двух конечных автоматов через тензорное произведение. Аналогично тому, как это было сделано в предыдущей домашней работе. Лучше сразу предусмотреть общий интерфейс функций, чтобы было проще ставить эксперименты.
- [ ] Подключить решение из предыдущей работы.
- [ ] Сформировать набор данных.
  - [ ] Выбрать все графы из раздела [RDF](https://jetbrains-research.github.io/CFPQ_Data/dataset/RDF.html).
  - [ ] Используя функцию из первой домашней работы узнать метки рёбер графов и на основе этой информации сформулировать не менее 4 различных запросов к каждому графу. Требования к запросам:
      - Запросы ко всем графам должны следовать некоторому общему шаблону. Например, если есть графы ```g1``` и ```g2``` с различными наборами меток, то ожидается, что запросы к ним будут выглядеть, например, так:
        - ```g1```:
          - ```(l1 | l2)* l3```
          - ```(l3 | l4)+ l1*```
          - ```l1 l2 l3 (l4|l1)*```
        - ```g2```:
          - ```(m1 | m3)* m2```
          - ```(m1 | m3)+ m2*```
          - ```m1 m2 m3 (m3|m1)*```
      - В запросах должны использоваться все общепринятые конструкции регулярных выражений  (замыкание, конкатенация, альтернатива). То есть хотя бы в одном запросе к каждому графу должна быть каждая из этих конструкций.
- [ ] С использованием сформированного набора данный провести сравнение производительности алгоритма, основанного на тензорном произведении, реализованного с использованием двух библиотек
  - sciPy (предыдущая работа)
  - pyCuBool (первый пункт этой работы)
- [ ] Оформить результаты экспериментов
- [ ] Провести анализ результатов
- [ ] Сделать notebook доступным по ссылке

[Ссылка на ноутбук](https://colab.research.google.com/drive/1UHRqHsM2yGc-2BbsHKo5tFMt0g8nfi-b?usp=sharing)

2021-10-11 08:40 UTC, vadyushkins requested changes
Здравствуйте!
Предоставьте доступ на комментирование к вашей юпите-тетрадке, пожалуйста. Если не получится, то сообщите мне, оставлю комментарии в пуллреквесте.

2021-10-13 16:51 UTC, bozhnyukAlex commented
Исправил замечания, в шапке обновил ссылку на ноутбук.

2021-10-19 07:48 UTC, vadyushkins requested changes
* Проблема №1. "(Best of 3)"
  * Непонятно какой именно результат замеров получается
* Проблема №2. "6 знаков после запятой"
  * С тремя замерами Вы не можете оценить даже первый десятичный знак

Остальные комментарии оставил в ноутбуке

> P.S. Так как требуется исправления уже после жесткого дедлайна, то за задачу не более `5.5` баллов

2021-11-04 13:48 UTC, vdshk approved these changes
Зачтено

2021-11-04 15:46 UTC, merged