[Task 6] CFG utils
bozhnyukAlex/formal-lang-course pull request #6
Opened 2021-10-16 19:36 UTC by bozhnyukAlex

## Задача

- [ ] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html) реализовать **функцию** преобразования контекстно-свободной грамматики в ослабленную нормальную форму Хомского.
- [ ] Предусмотреть возможность чтения грамматики из файла. Формат файла определяется возможностями pyformalng. Например, можно использовать [эту функцию](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html#pyformlang.cfg.CFG.from_text).
- [ ] Добавить необходимые тесты.

2021-10-19 08:52 UTC, vdshk requested changes
К сожалению в `pyformlang` строится не совсем ОНФХ, так как там удаляются `epsilon` в телах продукций. Однако на занятии проговаривалось, что в ОНФХ `epsilon` **остаются**.

Также я прошу Вас добавить тестов, отличных от тех, что используются [тут](https://github.com/kznts9v-1lya/formal-lang-course/pull/7)

- [ ] Стоит добавить тест на то, что получаемая ОНФХ совпадает с той, которую вы ожидаете получить

2021-10-19 08:52 UTC, vdshk commented on project/cfg_utils.py
> +    cnf = cfg.to_normal_form()
Это не ОНФХ. В ОНФХ в теле продукции может встречаться `epsilon`. Если посмотреть реализацию в `pyformlang`, то там в теле продукции не остается `epsilon`.

2021-10-19 08:52 UTC, vdshk commented on tests/test_cfg.py
> +    [("epsilon_cfg.txt", "epsilon"), ("class_example.txt", "S"), ("random.txt", "NP")],
Кажется тут всё-таки должно быть "E"
```suggestion
    [("epsilon_cfg.txt", "E"), ("class_example.txt", "S"), ("random.txt", "NP")],
```

2021-10-19 08:52 UTC, vdshk commented on tests/test_cfg.py
> +    [("epsilon_cfg.txt", "epsilon"), ("class_example.txt", "S"), ("random.txt", "NP")],
Если вы посмотрите на `cnf.productions`, то получите `set()`, хотя в ОНФХ было бы `E -> epsilon`

2021-10-25 16:23 UTC, vadyushkins requested changes
Есть небольшое замечание. Как исправите, - будет зачтено на полный балл

2021-10-25 16:23 UTC, vivalerievich commented on project/cfg_utils.py
> +def get_original_csg_from_file(path: str, start_symbol: str = None) -> CFG:
Мб так?
```suggestion
def get_original_cfg_from_file(path: str, start_symbol: str = None) -> CFG:
```

2021-10-25 18:26 UTC, bozhnyukAlex commented on project/cfg_utils.py
> +def get_original_csg_from_file(path: str, start_symbol: str = None) -> CFG:
Да.

2021-10-27 15:04 UTC, vadyushkins commented
Кажется `csg` вы не полностью убрали

2021-10-27 20:26 UTC, bozhnyukAlex commented
Теперь убрал полностью

2021-10-28 12:08 UTC, vadyushkins requested changes

2021-10-28 12:08 UTC, vivalerievich commented on tests/test_saving.py
> +#    assert info.edges_count == 5
Не, так не пойдет. Тесты с первой задачи должны остаться

2021-10-28 21:57 UTC, bozhnyukAlex commented on tests/test_saving.py
> +#    assert info.edges_count == 5
Сделано.

2021-10-29 10:56 UTC, vadyushkins approved these changes
Зачтено

2021-10-29 11:29 UTC, merged